import enum,uuid
from datetime import datetime,timezone
from sqlalchemy import *
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db.session import Base
def now():return datetime.now(timezone.utc)
def uid():return uuid.uuid4()
class Role(str,enum.Enum):
 ADMIN='ADMIN';ENGINEERING_DIRECTOR='ENGINEERING_DIRECTOR';ENGINEER='ENGINEER';TECHNICIAN='TECHNICIAN';AUDITOR='AUDITOR';VIEWER='VIEWER'
class Organization(Base):
 __tablename__='organizations';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);name:Mapped[str]=mapped_column(String(255));slug:Mapped[str]=mapped_column(String(100),unique=True);is_demo:Mapped[bool]=mapped_column(Boolean,default=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class User(Base):
 __tablename__='users';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);email:Mapped[str]=mapped_column(String(255),unique=True,index=True);full_name:Mapped[str]=mapped_column(String(255));hashed_password:Mapped[str]=mapped_column(String(255));role:Mapped[Role]=mapped_column(Enum(Role),default=Role.ENGINEER);org_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('organizations.id'));is_active:Mapped[bool]=mapped_column(Boolean,default=True);is_demo:Mapped[bool]=mapped_column(Boolean,default=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Site(Base):
 __tablename__='sites';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);org_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('organizations.id'));name:Mapped[str]=mapped_column(String(255));code:Mapped[str]=mapped_column(String(50));location:Mapped[str|None]=mapped_column(String(255));is_demo:Mapped[bool]=mapped_column(Boolean,default=False);meta:Mapped[dict]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class System(Base):
 __tablename__='systems';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);site_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('sites.id'));name:Mapped[str]=mapped_column(String(255));discipline:Mapped[str]=mapped_column(String(50));is_demo:Mapped[bool]=mapped_column(Boolean,default=False)
class Asset(Base):
 __tablename__='assets';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);site_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('sites.id'));system_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('systems.id'));tag:Mapped[str]=mapped_column(String(100),index=True);name:Mapped[str]=mapped_column(String(255));asset_type:Mapped[str]=mapped_column(String(100));manufacturer:Mapped[str|None]=mapped_column(String(255));model:Mapped[str|None]=mapped_column(String(255));status:Mapped[str]=mapped_column(String(50),default='operational');specs:Mapped[dict]=mapped_column(JSON,default=dict);is_demo:Mapped[bool]=mapped_column(Boolean,default=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class AssetRelation(Base):
 __tablename__='asset_relations';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);from_asset_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('assets.id'));to_asset_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('assets.id'));relation_type:Mapped[str]=mapped_column(String(50));meta:Mapped[dict]=mapped_column(JSON,default=dict)
class Document(Base):
 __tablename__='documents';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);org_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('organizations.id'));site_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('sites.id'));title:Mapped[str]=mapped_column(String(255));filename:Mapped[str]=mapped_column(String(255));content_type:Mapped[str]=mapped_column(String(100));storage_key:Mapped[str]=mapped_column(String(512));size_bytes:Mapped[int]=mapped_column(Integer,default=0);status:Mapped[str]=mapped_column(String(50),default='uploaded');is_demo:Mapped[bool]=mapped_column(Boolean,default=False);meta:Mapped[dict]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);created_by:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('users.id'))
class DocumentChunk(Base):
 __tablename__='document_chunks';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);document_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('documents.id'));chunk_index:Mapped[int]=mapped_column(Integer);content:Mapped[str]=mapped_column(Text);embedding:Mapped[list|None]=mapped_column(JSON);meta:Mapped[dict]=mapped_column(JSON,default=dict)
class Project(Base):
 __tablename__='projects';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);org_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('organizations.id'));site_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('sites.id'));name:Mapped[str]=mapped_column(String(255));code:Mapped[str]=mapped_column(String(50));description:Mapped[str|None]=mapped_column(Text);status:Mapped[str]=mapped_column(String(50),default='active');capex_estimate:Mapped[float|None]=mapped_column(Float);currency:Mapped[str]=mapped_column(String(10),default='USD');is_demo:Mapped[bool]=mapped_column(Boolean,default=False);meta:Mapped[dict]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Calculation(Base):
 __tablename__='calculations';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);org_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('organizations.id'));project_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('projects.id'));discipline:Mapped[str]=mapped_column(String(50));calc_type:Mapped[str]=mapped_column(String(100));name:Mapped[str]=mapped_column(String(255));inputs:Mapped[dict]=mapped_column(JSON);formula:Mapped[str]=mapped_column(Text);units:Mapped[dict]=mapped_column(JSON);assumptions:Mapped[list]=mapped_column(JSON);result:Mapped[dict]=mapped_column(JSON);check_status:Mapped[str]=mapped_column(String(50));check_notes:Mapped[str|None]=mapped_column(Text);source:Mapped[str]=mapped_column(String(255));version:Mapped[str]=mapped_column(String(50));engine_module:Mapped[str]=mapped_column(String(255));created_by:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('users.id'));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Drawing(Base):
 __tablename__='drawings';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);org_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('organizations.id'));project_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('projects.id'));name:Mapped[str]=mapped_column(String(255));drawing_type:Mapped[str]=mapped_column(String(50),default='schematic');schema_version:Mapped[str]=mapped_column(String(20),default='1.0');viewport:Mapped[dict]=mapped_column(JSON,default=dict);is_demo:Mapped[bool]=mapped_column(Boolean,default=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now);nodes=relationship('DrawingNode',cascade='all, delete-orphan');edges=relationship('DrawingEdge',cascade='all, delete-orphan')
class DrawingNode(Base):
 __tablename__='drawing_nodes';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);drawing_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('drawings.id'));node_key:Mapped[str]=mapped_column(String(100));node_type:Mapped[str]=mapped_column(String(50));label:Mapped[str]=mapped_column(String(255));position_x:Mapped[float]=mapped_column(Float,default=0);position_y:Mapped[float]=mapped_column(Float,default=0);asset_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('assets.id'));data:Mapped[dict]=mapped_column(JSON,default=dict)
class DrawingEdge(Base):
 __tablename__='drawing_edges';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);drawing_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('drawings.id'));edge_key:Mapped[str]=mapped_column(String(100));source_key:Mapped[str]=mapped_column(String(100));target_key:Mapped[str]=mapped_column(String(100));label:Mapped[str|None]=mapped_column(String(255));edge_type:Mapped[str]=mapped_column(String(50),default='default');data:Mapped[dict]=mapped_column(JSON,default=dict)
class AgentRun(Base):
 __tablename__='agent_runs';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);org_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('organizations.id'));user_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('users.id'));provider:Mapped[str]=mapped_column(String(50));model:Mapped[str]=mapped_column(String(100));status:Mapped[str]=mapped_column(String(50));prompt:Mapped[str]=mapped_column(Text);response:Mapped[str|None]=mapped_column(Text);meta:Mapped[dict]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class ToolCall(Base):
 __tablename__='tool_calls';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);agent_run_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('agent_runs.id'));tool_name:Mapped[str]=mapped_column(String(100));arguments:Mapped[dict]=mapped_column(JSON);result:Mapped[dict|None]=mapped_column(JSON);status:Mapped[str]=mapped_column(String(50));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class AuditEvent(Base):
 __tablename__='audit_events';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);org_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('organizations.id'));user_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('users.id'));action:Mapped[str]=mapped_column(String(100));resource_type:Mapped[str]=mapped_column(String(100));resource_id:Mapped[str|None]=mapped_column(String(100));detail:Mapped[dict]=mapped_column(JSON,default=dict);ip_address:Mapped[str|None]=mapped_column(String(50));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
